//
//  UIColor+Additions.swift
//
//  Generated by Zeplin on 1/13/18.
//  Copyright (c) 2018 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var paleGrey: UIColor { 
		return UIColor(red: 230.0 / 255.0, green: 234.0 / 255.0, blue: 238.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var charcoalGrey: UIColor { 
		return UIColor(red: 67.0 / 255.0, green: 71.0 / 255.0, blue: 75.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var silver: UIColor { 
		return UIColor(red: 212.0 / 255.0, green: 217.0 / 255.0, blue: 222.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var coolGrey: UIColor { 
		return UIColor(red: 164.0 / 255.0, green: 173.0 / 255.0, blue: 180.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var brightLightBlue: UIColor { 
		return UIColor(red: 52.0 / 255.0, green: 205.0 / 255.0, blue: 254.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var darkBlueGrey: UIColor { 
		return UIColor(red: 9.0 / 255.0, green: 25.0 / 255.0, blue: 38.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var lightGreenishBlue: UIColor { 
		return UIColor(red: 94.0 / 255.0, green: 245.0 / 255.0, blue: 213.0 / 255.0, alpha: 1.0)
	}
    
    //My...Colors
    @nonobjc class var selectedGrey: UIColor {
        return UIColor(red: 9.0 / 255.0, green: 25.0 / 255.0, blue: 38.0 / 255.0, alpha: 1.5)
    }
     
    @nonobjc class var clearBlack: UIColor {
        return UIColor(red: 0.0 / 255.0, green: 0.0 / 255.0, blue: 0.0 / 255.0, alpha: 0.0)
    }
    
    @nonobjc class var clearBlackWith50Opc: UIColor {
        return UIColor(red: 0.0 / 255.0, green: 0.0 / 255.0, blue: 0.0 / 255.0, alpha: 0.5)
    }
}
